### PR TITLE
Fix license combobox

### PR DESCRIPTION
**Pull request by nicolaskempf57**

### CODE REVIEW

**Review by maudetes — COMMENTED** [review]
I'm confused about what we're trying to fix :p

**Comment by nicolaskempf57** [comment]
> I'm confused about what we're trying to fix :p

The current implementation isn't working for license that are available for both the public services and the other organizations, the hover effect is missing

**Review by ThibaudDauce — APPROVED** [review]
Seems fine! The checkmark is much better :D 

image

Is it missing a margin between checkmark and label in frequencies select?

**Comment by nicolaskempf57** [comment]
> Is it missing a margin between checkmark and label in frequencies select?

Indeed, now using a gap to work with this case too

**Pull request merged**
